#!/usr/bin/env bash

. /root/fs-env

# welcome to grub 1
# hahahaha
mkdir -p /boot/grub
cp /usr/share/grub/x86_64-redhat/* /boot/grub

# find boot partition
bootpart="$(df -P /boot | tail -1)"
bootpart="${bootpart/ */}"
bootpart="${bootpart/*[^0-9]/}"
(( bootpart-- ))

for d in ${BIOS_BOOTDEVS} ; do
  d=${d/[0-9]/}
  printf '(hd0) %s\n' ${d} > /boot/grub/device.map
  printf 'root (hd0,%s)\nsetup (hd0)\n' "${bootpart}" | /bin/env PATH=/bin:/usr/bin:/sbin:/usr/sbin /sbin/grub --device-map=/boot/grub/device.map
done
